---
title: "Practical Machine Learning - Course Project"
author: "lak55"
---

## Synopsis


## Loading and preprocessing the data

1. Load the libraries 

```{r}
library(Hmisc)
library(randomForest)
library(pROC)
library(caret)
library(kernlab)
library(ggplot2)
library(rpart)
library(rpart.plot)
library(RColorBrewer)
library(foreach)

```

2. Load the data

```{r}
myTrainData <- read.csv("C:\\Users\\Mardi\\ds2015\\repo\\pml-training.csv",header=TRUE, sep = ",")
myTestData <- read.csv("C:\\Users\\Mardi\\ds2015\\repo\\pml-testing.csv",header=TRUE, sep = ",")
set.seed(12345)
```

3. Clean and pre-processing the "myTrainData" dataset

```{r}
training_data <- read.csv("pml-training.csv", na.strings=c("#DIV/0!") )
testing_data <- read.csv("pml-testing.csv", na.strings=c("#DIV/0!") )
```

```{r}
for(i in c(8:ncol(training_data)-1)) {training_data[,i] = as.numeric(as.character(training_data[,i]))}

for(i in c(8:ncol(testing_data)-1)) {testing_data[,i] = as.numeric(as.character(testing_data[,i]))}
```

4. Choose model and train
```{r}
feature_set <- colnames(training_data[colSums(is.na(training_data)) == 0])[-(1:7)]
model_data <- training_data[feature_set]
feature_set

idx <- createDataPartition(y=model_data$classe, p=0.75, list=FALSE )
training <- model_data[idx,]
testing <- model_data[-idx,]

```

5. Partitioning Data

```{r}

x <- training[-ncol(training)]
y <- training$classe

rf <- foreach(ntree=rep(150, 6), .combine=randomForest::combine, .packages='randomForest') %dopar% {
  randomForest(x, y, ntree=ntree) }


predictions1 <- predict(rf, newdata=training)
confusionMatrix(predictions1,training$classe)


predictions2 <- predict(rf, newdata=testing)
confusionMatrix(predictions2,testing$classe)

pml_write_files = function(x){
  n = length(x)
  for(i in 1:n){
    filename = paste0("problem_id_",i,".txt")
    write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
}


x <- testing_data
x <- x[feature_set[feature_set!='classe']]
answers <- predict(rf, newdata=x)

answers

pml_write_files(answers)

```





